version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-example
    container_name: go-exmaple
    command: ./test-golang
    restart: unless-stopped
    working_dir: /app
    ports:
      - 8000:8000
    volumes:
      - ./storage:/app/storage
    environment:
      DB_USER: root
      DB_HOST: mysql:3306
      DB_NAME: docker_test
      DB_PASSWORD: secret
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: docker_test

volumes:
  mysql-data:
    name: mysql-data